- Algorithms/BinaryLifting.cpp
Added Binary Lifting snippet. Issue #2
> BinaryLifting.cpp

- Algorithms/Sorting/RadixSort.py
Ref #2
This code snippet adds the conventional radix sort method to the repo.
Signed-off-by: Aritra Majumder <aritramajumder8438@gmail.com>
> feat: Add Radix Sort

- Algorithms/sorting/CountSort.py
Ref #2.
Adds traditional count sort.
Signed-off-by: Aritra Majumder <aritramajumder8438@gmail.com>
> feat: Add Count Sort

- Algorithms/Divide and Conquer/karatsuba_multiplication.py
Ref #2.
Add the Karatsuba method for fast multiplication.
Signed-off-by: Aritra Majumder <aritramajumder8438@gmail.com>
> feat: Add Karatsuba multiplication

- Algorithms/Sorting/MergeSort.py
Ref #2.
Add traditional `merge sort` algorithm
Signed-off-by: Aritra Majumder <aritramajumder8438@gmail.com>
> feat: Add `Merge Sort`

- Algorithms/Linked List/Circular Linked List.cpp
- Algorithms/Linked List/Doubly Linked List.cpp
- Algorithms/Linked List/Singly Linked List.cpp
- Algorithms/Queue/Double Ended Queue.cpp
- Algorithms/Queue/Queue using circular linked list.cpp
> Linked List algo added

- Algorithms/Divide and Conquer/karatsuba_multiplication.cpp
I have created the divide-and-conquer algorithm in C++.
> create a karatsuba_multiplication.cpp for divide&conquer

- Algorithms/Tree Algorithms/Diameter_Of_Tree.cpp
Hey @kanha-gupta I have successfully added the program to calculate the diameter of a tree. So please accept this PR under the tag of Hacktoberfest2023
> Added the program to calculate diameter of a tree

- Web-Development/REACT/Component.jsx
- Web-Development/REACT/ContextProvider.jsx
- Web-Development/REACT/Readme.md
Hi,
I have added react snippets to create functional and arrow based components and snippet for creating ContextAPI.
Please merge this PR.
> Added React based snippets

- Web-Development/JAVASCRIPT/basicJavascript.js
Snippet Code for Smooth anchor link action
> Code anchor

- Web-Development/RABBITMQ - GO/main.go
Hello @kanha-gupta here is code snippet using in event driven microservices using go
> feat: add snippet for rabbitmq in go

- Algorithms/Kadane's algorithm/kadane_algo.cpp
Added new algorithm 
-Kadane's algorithm
> Added Kadane's Algorithm

- Web-Development/MongoDB/connect&schema.js
Please add hacjtoberfest label after merging. 
Thanks!
> feat: MongoDB basic snippet

- Algorithms/Sorting/BubbleSort.cpp
- Algorithms/Sorting/InsertionSort.py
This is an optimized code for bubble sort in C++.
> Bubble Sort

- Web-Development/CustomRadio/css/style.css
- Web-Development/CustomRadio/index.html
> feat: Custom input radio

- Algorithms/Graph Search Algorithm/Dijkstra.cpp
added code for Dijkstra's Algorithm .
> added code for Dijkstra's Algorithm

- Web-Development/HTML/htmlModal.html
Added htmlModal file to HTML folder
> Create htmlModal file

- Algorithms/Searching Algo/Randomized Select.cpp
> Randomized Select.cpp added

- Web-Development/JAVASCRIPT/fetchAPI.js
Please add hacktoberfest label after review and merge.
Thanks!
> feat: Added fetchAPI for Javascript

- Language-Specific/Hello World/R/HelloWorld.r
Ref #4 
adding Hello World in r language
> Add HelloWorld in R language

- Algorithms/Tree Algorithms/LCA_binarytree.cpp
hello sir , 
i have added the algorithm for finding lowest common ancestor of a binary tree in c++ 
please review it
> added LCA algorithm

- Algorithms/DisjointSet/DisjointSet.cpp
> Code Snippet - Algorithms(Disjoint Set)

- Algorithms/LCS.cpp
- Algorithms/Shortest Distance/Dijkstra.cpp
This code demonstrates a dynamic programming approach to solve the LCS problem between two strings.
> added a longest common subsequence of string programs algorithm

- Language-Specific/Python/Functions.py
- Language-Specific/Python/Most-used-code-snippets.py
Adding code snippets of Python having two files containing some basic syntax codes and functions.
This PR resolves the issue #4
> Adding python code

- Web-Development/Django/formsAndAuthentication.py
Please add Hacktoberfest label after review, enjoyed working!
> feat: Added Django forms and Authentication.
